### ISSUE TITLE
Add loading

### ISSUE THREAD

**Issue by sotayamashita** [sotayamashita/dotfiles#12]
- https://github.com/sindresorhus/ora/blob/master/index.js 
- https://github.com/fisherman/fisherman/search?q=gif&type=Code&utf8=%E2%9C%93
- https://github.com/helloIAmPau/node-spinner

**Comment by ghost** [comment]
https://github.com/fisherman/spin ?

**Comment by sotayamashita** [comment]
@bucaran Thanks. I forgot about it. 😢
